name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: I'm trying to... but I can't because...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: api-example
    attributes:
      label: API Example
      description: Show how you envision using this feature
      render: csharp
      placeholder: |
        var processor = new TaskListProcessorEnhanced("Example", logger);

        // Your proposed API usage
        await processor.YourNewFeature(...);
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions or workarounds have you considered?
      placeholder: I've tried... but it doesn't work because...
    validations:
      required: false

  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: How important is this feature to you?
      options:
        - Critical - Blocking my use of TaskListProcessor
        - High - Would significantly improve my workflow
        - Medium - Would be nice to have
        - Low - Minor convenience
    validations:
      required: true

  - type: dropdown
    id: willing-to-contribute
    attributes:
      label: Contribution
      description: Would you be willing to contribute this feature?
      options:
        - Yes, I can submit a PR
        - Maybe, with guidance
        - No, but I can help test
        - No
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples
      placeholder: Any other relevant information...
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: This feature aligns with TaskListProcessor's goals (async task orchestration)
          required: true
        - label: I have considered backward compatibility
          required: false
